<a href="https://colab.research.google.com/github/Shahanas2003/digit_recognizer/blob/main/digit_recognizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
import numpy as np
from tensorflow.keras.datasets import mnist
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
import joblib

# Load MNIST dataset
(x_train, y_train), (x_test, y_test) = mnist.load_data()


In [32]:
x_train = x_train.reshape(-1, 28*28) / 255.0
x_test = x_test.reshape(-1, 28*28) / 255.0


In [22]:
model = LogisticRegression(max_iter=1000, solver='lbfgs', multi_class='multinomial')
model.fit(x_train, y_train)


/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=1000, multi_class='multinomial')

In [33]:
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Test accuracy: {accuracy * 100:.2f}%")

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

# Confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Test accuracy: 92.59%

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.96      0.98      0.97      1135
           2       0.93      0.90      0.92      1032
           3       0.90      0.91      0.91      1010
           4       0.94      0.94      0.94       982
           5       0.89      0.87      0.88       892
           6       0.94      0.95      0.95       958
           7       0.93      0.92      0.93      1028
           8       0.88      0.88      0.88       974
           9       0.91      0.92      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.93      0.93      0.93     10000


Confusion Matrix:
[[ 958    0    1    3    1    9    4    3    1    0]
 [   0 1111    5    2    0    2    3    1   11    0]
 [   6    9  931   16   10    3   12   10   31    4]
 [   4    1   17 

In [24]:
joblib.dump(model, "logistic_model.pkl")
print("Model saved to logistic_model.pkl")


Model saved to logistic_model.pkl


In [25]:
# Load model
loaded_model = joblib.load("logistic_model.pkl")

# Example: predict on a new sample (assuming x_sample is preprocessed)
# prediction = loaded_model.predict(x_sample)


In [27]:
# Load model
loaded_model = joblib.load("logistic_model.pkl")

# Example: predict on a new sample (assuming x_sample is preprocessed)
# prediction = loaded_model.predict(x_sample)


In [28]:
# Load model
loaded_model = joblib.load("logistic_model.pkl")

# Example: predict on a new sample (assuming x_sample is preprocessed)
# prediction = loaded_model.predict(x_sample)


In [30]:
#Create the app.py file inside Colab

%%writefile app.py
import streamlit as st
import numpy as np
from PIL import Image, ImageOps
import joblib
import os

# App title
st.set_page_config(page_title="Digit Classifier", page_icon="✍️")
st.title("🧠 Handwritten Digit Classifier (Logistic Regression)")

st.markdown("""
Upload an image of a handwritten digit (28x28 pixels, grayscale). The model will predict the digit using Logistic Regression.
""")

MODEL_PATH = "logistic_model.pkl"

# Load model
if not os.path.exists(MODEL_PATH):
    st.error("Model file not found! Please ensure 'logistic_model.pkl' is present.")
    st.stop()

model = joblib.load(MODEL_PATH)

# Upload image
uploaded_file = st.file_uploader("Upload a digit image", type=["png", "jpg", "jpeg"])

if uploaded_file:
    # Preprocess the image
    image = Image.open(uploaded_file).convert("L")  # Convert to grayscale
    image = ImageOps.invert(image)                 # Invert image (black background to white digit)
    image = image.resize((28, 28))                 # Resize to MNIST format

    st.image(image, caption="Processed Image", width=150)

    # Convert image to input format
    img_array = np.array(image).astype("float32") / 255.0
    img_flattened = img_array.reshape(1, -1)

    # Predict
    prediction = model.predict(img_flattened)[0]
    st.success(f"✅ Predicted Digit: **{prediction}**")


Overwriting app.py
